// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFoxZJsFzc7ssweiS0fjlUDz2ppWIviAk',
    appId: '1:517379996819:web:379ef1bfbded9b9dc1a166',
    messagingSenderId: '517379996819',
    projectId: 'books-fc2b5',
    authDomain: 'books-fc2b5.firebaseapp.com',
    storageBucket: 'books-fc2b5.firebasestorage.app',
    measurementId: 'G-JEKPSHEGGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGvICPkV2nEi6mtlrGpxoEhWjCK6kbjI',
    appId: '1:517379996819:android:0061ffb4b93ecb66c1a166',
    messagingSenderId: '517379996819',
    projectId: 'books-fc2b5',
    storageBucket: 'books-fc2b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACtFC0_hbykkchJu2yh4_C1iSOYDtqlA',
    appId: '1:517379996819:ios:0dbec31a6efb2b80c1a166',
    messagingSenderId: '517379996819',
    projectId: 'books-fc2b5',
    storageBucket: 'books-fc2b5.firebasestorage.app',
    iosBundleId: 'com.example.readauraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACtFC0_hbykkchJu2yh4_C1iSOYDtqlA',
    appId: '1:517379996819:ios:0dbec31a6efb2b80c1a166',
    messagingSenderId: '517379996819',
    projectId: 'books-fc2b5',
    storageBucket: 'books-fc2b5.firebasestorage.app',
    iosBundleId: 'com.example.readauraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFoxZJsFzc7ssweiS0fjlUDz2ppWIviAk',
    appId: '1:517379996819:web:1a1663ca149ddad3c1a166',
    messagingSenderId: '517379996819',
    projectId: 'books-fc2b5',
    authDomain: 'books-fc2b5.firebaseapp.com',
    storageBucket: 'books-fc2b5.firebasestorage.app',
    measurementId: 'G-XB1K11V2P8',
  );

}